apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    service.type: instrumentation
  labels:
    io.kompose.service: pyroscope
  name: pyroscope
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyroscope
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
        service.type: instrumentation
      labels:
        io.kompose.service: pyroscope
    spec:
      containers:
        - image: grafana/pyroscope:1.14.0@sha256:0f63959ffcf217e7046d8f7a3d20cf6909f2924f885fc2f0eec58f87f9acf749
          name: pyroscope
          ports:
            - containerPort: 4040
              protocol: TCP
      restartPolicy: Always
